modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/customized-dungeon-loot/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="minecraft:chest"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/CDL.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/customized-dungeon-loot"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''Adds vanilla items with special abilities to the dungeon chests, like enchantments, custom names, attributes and more cool features!
'''


[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

