modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/customized-dungeon-loot/issues"

[[mods]]
modId="cdl"
version="2.1.2"
displayName="Customized Dungeon Loot"
itemIcon="minecraft:chest"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/CDL.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/customized-dungeon-loot"
logoFile="logo.png"
credits=""
authors="XxRexRaptorxX (RexRaptor)"
description='''
 Adds vanilla items with special abilities to the dungeon chests, like enchantments, custom names, attributes and more cool features!
 '''

[[dependencies.cdl]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.98,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cdl]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
