modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory (26 is current forge version)
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/customized-dungeon-loot/issues" #optional

[[mods]] #mandatory
modId="cdl" #mandatory
version="2.1.1" #mandatory
displayName="Customized Dungeon Loot" #mandatory
itemIcon="minecraft:chest"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/CDL.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/customized-dungeon-loot" #optional
logoFile="logo.png" #optional
credits="" #optional
authors="XxRexRaptorxX (RexRaptor)" #optional
description='''
 Adds vanilla items with special abilities to the dungeon chests, like enchantments, custom names, attributes and more cool features!
 '''

[[dependencies.cdl]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.cdl]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
