modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/customized-dungeon-loot/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="minecraft:chest"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/CDL_NEO.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/customized-dungeon-loot"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''Fills the crates of the various structures in Minecraft with modified vanilla loot to find even more unique and special items!'''

[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"


